export const cityCountryMap: Record<string, string> = {
  "Tokyo": "Japan",
  "New York": "USA",
  "London": "UK",
  "Paris": "France",
  "Shanghai": "China",
  "Sao Paulo": "Brazil",
  "Mumbai": "India",
  "Mexico City": "Mexico",
  "Beijing": "China",
  "Osaka": "Japan",
  "Cairo": "Egypt",
  "Dhaka": "Bangladesh",
  "Karachi": "Pakistan",
  "Buenos Aires": "Argentina",
  "Istanbul": "Turkey",
  "Kolkata": "India",
  "Manila": "Philippines",
  "Lagos": "Nigeria",
  "Rio de Janeiro": "Brazil",
  "Tianjin": "China",
  "Kinshasa": "DR Congo",
  "Guangzhou": "China",
  "Los Angeles": "USA",
  "Moscow": "Russia",
  "Shenzhen": "China",
  "Lahore": "Pakistan",
  "Bangalore": "India",
  "Bogota": "Colombia",
  "Jakarta": "Indonesia",
  "Chennai": "India",
  "Lima": "Peru",
  "Bangkok": "Thailand",
  "Seoul": "South Korea",
  "Nagoya": "Japan",
  "Hyderabad": "India",
  "Chicago": "USA",
  "Chengdu": "China",
  "Nanjing": "China",
  "Wuhan": "China",
  "Ho Chi Minh City": "Vietnam",
  "Luanda": "Angola",
  "Ahmedabad": "India",
  "Kuala Lumpur": "Malaysia",
  "Xi'an": "China",
  "Hong Kong": "China",
  "Dongguan": "China",
  "Hangzhou": "China",
  "Foshan": "China",
  "Shenyang": "China",
  "Riyadh": "Saudi Arabia",
  "Baghdad": "Iraq",
  "Santiago": "Chile",
  "Surat": "India",
  "Madrid": "Spain",
  "Pune": "India",
  "Harbin": "China",
  "Houston": "USA",
  "Dallas": "USA",
  "Toronto": "Canada",
  "Dar es Salaam": "Tanzania",
  "Miami": "USA",
  "Belo Horizonte": "Brazil",
  "Singapore": "Singapore",
  "Philadelphia": "USA",
  "Atlanta": "USA",
  "Fukuoka": "Japan",
  "Khartoum": "Sudan",
  "Barcelona": "Spain",
  "Johannesburg": "South Africa",
  "Saint Petersburg": "Russia",
  "Qingdao": "China",
  "Dalian": "China",
  "Washington": "USA",
  "Yangon": "Myanmar",
  "Alexandria": "Egypt",
  "Jinan": "China",
  "Guadalajara": "Mexico",
  "Berlin": "Germany",
  "Sydney": "Australia",
  "Melbourne": "Australia",
  "Rome": "Italy",
  "Dubai": "UAE",
  "Vancouver": "Canada",
  "Montreal": "Canada",
  "Nairobi": "Kenya",
  "Hanoi": "Vietnam",
  "Casablanca": "Morocco",
  "Caracas": "Venezuela",
  "Taipei": "Taiwan",
  "Kumasi": "Ghana",
  "Cape Town": "South Africa",
  "San Francisco": "USA",
  "Milan": "Italy",
  "Munich": "Germany",
  "Vienna": "Austria",
  "Stockholm": "Sweden",
  "Prague": "Czech Republic",
  "Warsaw": "Poland",
  "Budapest": "Hungary",
  "Copenhagen": "Denmark",
  "Dublin": "Ireland",
  "Guayaquil": "Ecuador",
  "Quito": "Ecuador"
};

export const getCountry = (city: string) => cityCountryMap[city] || "Unknown";
